# ===========================================
# DOCKER COMPOSE - COOLIFY DEPLOY
# ===========================================

version: '3.8'

services:
  figma-agenti-backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    
    container_name: figma-agenti-backend
    
    ports:
      - "3000:3000"
    
    environment:
      # Configurações básicas
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      
      # Chaves de API (configurar no Coolify)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      
      # Modelos de IA
      - MODELO_VISION=${MODELO_VISION:-gpt-4o-mini}
      - MODELO_TEXTO=${MODELO_TEXTO:-gpt-5-mini}
      - MODELO_AGENTE_A=${MODELO_AGENTE_A:-gpt-5-mini}
      - MODELO_AGENTE_B=${MODELO_AGENTE_B:-gpt-4o-mini}
      - MODELO_AGENTE_C=${MODELO_AGENTE_C:-o3-mini}
      
      # Configurações de temperatura
      - TEMP_VISION=${TEMP_VISION:-0.1}
      - TEMP_TEXTO=${TEMP_TEXTO:-0.2}
      - MAX_TOKENS_VISION=${MAX_TOKENS_VISION:-4096}
      - MAX_TOKENS_TEXTO=${MAX_TOKENS_TEXTO:-50000}
      
      # Configurações gerais
      - CORS_ORIGIN=${CORS_ORIGIN:-https://www.figma.com}
      - CLEANUP_TEMP_FILES=${CLEANUP_TEMP_FILES:-true}
      - DEBUG_FILES_RETENTION_DAYS=${DEBUG_FILES_RETENTION_DAYS:-7}
      - RETRY_ATTEMPTS=${RETRY_ATTEMPTS:-3}
      - RETRY_DELAY=${RETRY_DELAY:-1000}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30000}
      - ANALYZE_IMAGES=${ANALYZE_IMAGES:-true}
      - REASONING_EFFORT=${REASONING_EFFORT:-medium}
      - MAXTOK_TEXTO=${MAXTOK_TEXTO:-20000}
    
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/ping-openai', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    # Recursos limitados
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Volumes para logs e debug
    volumes:
      - ./logs:/app/logs
      - ./debug_responses:/app/debug_responses
      - ./debug_layouts:/app/debug_layouts
      - ./debug_vision:/app/debug_vision
      - ./temp:/app/temp

networks:
  default:
    name: figma-agenti-network
