# ===========================================
# FIGMA-AGENTI - DOCKER COMPOSE
# ===========================================

services:
  # Serviço principal do backend
  figma-agenti-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: figma-agenti-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.example
    volumes:
      # Volume para logs persistentes
      - ./logs:/app/logs
      # Volume para arquivos temporários
      - ./temp:/app/temp
      # Volume para debug (opcional)
      - ./debug:/app/debug
    networks:
      - figma-agenti-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/ping-openai', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Limites de recursos
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Nginx como proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    container_name: figma-agenti-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - figma-agenti-backend
    networks:
      - figma-agenti-network
    profiles:
      - production

networks:
  figma-agenti-network:
    driver: bridge
    name: figma-agenti-network

volumes:
  logs:
    driver: local
  temp:
    driver: local
  debug:
    driver: local
